### ISSUE TITLE
put_gcode_file payload type if it normal string or ascii values string

### ISSUE THREAD

**Issue by srinivas365** [re-3D/opengb-web#2]
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "put_gcode_file",
    "params": {
        "name": "test_cube.gco",
        "payload": "<gcode>"
    }
}

Please tell me the payload data type if it ascii data type please tell me how to convert it ti ascii

**Comment by amorphic** [comment]
As per the [docs](https://opengb.readthedocs.io/en/latest/api.html#put-gcode-file) it's just the gcode represented as a string of ascii characters.

[Gcode is just text](https://reprap.org/wiki/G-code) so there's no conversion to do as such.

**Comment by srinivas365** [comment]
we will get a gcode file from slicing software. After reading the contents of that file into string data type. should we need to convert the characters in string to ascii characters and give to payload parameter or can we directly give to payload as a string

i.e if gcode file contains AB
what is string given to payload parameter
is it AB or 6566

I have gcode file as output from slicing software please tell me how to give this as input to 3d parameter in detail 

I am new to this domain. Please help me 

Thanks in advance

**Comment by amorphic** [comment]
`AB`

**Comment by srinivas365** [comment]
Thank you
